### ISSUE TITLE
Username italic with arrow

### ISSUE THREAD

**Issue by wintstar** [wintstar/AJAX-Chat#3]
@zwiebus,I will add your suggestion to the next update.

![user_menue-link](https://github.com/wintstar/AJAX-Chat/assets/2753863/fb2e2910-b4e9-4a2a-a402-19c10c7ac545)

**Comment by wintstar** [comment]
Please describe in more detail what exactly it should be, why with arrow. What is its purpose? I don't understand it at the moment.

**Comment by zwiebus** [comment]
The point is that when many people are posting, it can go unnoticed that a user has written to you. So you can see much better that you have been contacted if you send the message with the changed username with an arrow.

**Comment by wintstar** [comment]
Angled quotation marks are more suitable. It also looks better. In addition, grab cursor would be appropriate as a hint with the mouse.

![issue3](https://github.com/wintstar/AJAX-Chat/assets/2753863/37971521-1471-4c29-ad53-ba5f1c20fab6)

**Comment by wintstar** [comment]
Inserted, many thanks @zwiebus.
