### ISSUE TITLE
Better placement for "returnchatButton"

### ISSUE THREAD

**Issue by zwiebus** [wintstar/AJAX-Chat#5]
How about placing the returnchatbutton at the bottom left in logs ?
It is easy to overlook it at the top and in some styles it overlaps with the selection fields.

You could do this in any style with :
```
#content a#returnchatButton {
        position: fixed;
        left: 50px
        bottom: 20px;
}
```

**Comment by wintstar** [comment]
Very good idea, I will add it with the next commit. Many thanks @zwiebus 


**Mobil**
```
@media (max-width: 700px) {
	#content a#returnchatButton { position: fixed; left: 5px; display: block; bottom: 40px; }
}
```
![mobil-logs-return-button](https://github.com/wintstar/AJAX-Chat/assets/2753863/b84ed506-eefe-430f-b104-42a87e37c5ee)


**Desktop**
```
#content a#returnchatButton {
	position: fixed;
	left: 20px;
	bottom: 60px;
}
```

![desktop-logs-return-button](https://github.com/wintstar/AJAX-Chat/assets/2753863/528e60cd-838c-423d-8597-c03d9e8ab56c)

**Comment by wintstar** [comment]
Added with https://github.com/wintstar/AJAX-Chat/commit/a1e81de5d7481baabac087faee65a2a8df76ab4c

**Comment by wintstar** [comment]
So far I only see one problem in the style XenForo.

![XenForo-Bug-Return](https://github.com/wintstar/AJAX-Chat/assets/2753863/10d5753e-0310-49fa-a339-812b3513d676)


And I have inserted an error:

```
#content a#returnchatButton {
	position: fixed;
	left: 20px;
	bottom: 60px;
}
```
This is wrong, should be absolute.


I will fix this in the next few days.

**Comment by wintstar** [comment]
### Styles fixed
```[tasklist]
- [ ] beige
- [ ] black
- [ ] grey
- [ ] Oxygen
- [ ] Lithium
- [ ] Sulfur
- [ ] Cobalt
- [ ] Mercury
- [ ] Uranium
- [ ] Pine
- [ ] Plum
- [ ] prosilver
- [ ] Core
- [ ] Curve
- [ ] MyBB
- [ ] vBulletin
- [ ] XenForo
```

**Comment by wintstar** [comment]
@zwiebus, it should be okay now. Please take a look and please give feedback. Thanks

https://github.com/wintstar/AJAX-Chat/commit/f426c440083ea14cb47454c1e43a1390bc23c5a3

**Comment by wintstar** [comment]
There are too many conflicts with the current layout.

I'll create a new one. The last commit there was a problem with the submit button. I also don't like the copyright in the header. I'm thinking about mobile design. With the commit in the branch style I reset to the status of 0.9.0-standalone-w1.

https://github.com/wintstar/AJAX-Chat/commit/e7bda924bea4d479d42725249f60d7f07ec0dd7e

**Comment by zwiebus** [comment]
Ah okay . I was using my own style and had the button defined there instead in global.css, so I will do it that way again for now and wait for the new layout.

**Comment by wintstar** [comment]
This commit https://github.com/wintstar/AJAX-Chat/commit/131cf6502904e3059218611666466b8c6c79e9fd is an 'intermediate solution' until the new layout is ready. I will create the new layout later.

> I was using my own style and had the button defined there instead in global.css

Basically no change is made in the global.css. If you want to use your own style, you have to create your own css file for it. In this css file you can change the chat to your own style.

**Comment by zwiebus** [comment]
> you have to create your own css file for it. In this css file you can change the chat to your own style. 

You have misunderstood. i made my own _style.css_ a long time ago and adapted it when i switched to psr-4. I also have a modified global.css (and other files) because I have added new functions such as "news", "userlist", "fileupload" etc. to the chat. You can see that I cannot adopt your changes one-to-one and have to rework them manually for my own purposes ...
